/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.atm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class FASTCASH extends javax.swing.JFrame {

    /**
     * Creates new form FASTCASH
     */
    public FASTCASH() {
        initComponents();
    }
    int MyAccNum;
    public FASTCASH(int AccNum) {
        initComponents();
        MyAccNum=AccNum;
        GetBalance();
    }
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet Rs= null;
    Statement St = null;
    int oldbalance;
    private void GetBalance()
    {
        String Query = "SELECT * FROM accounttbl WHERE ACC_NO='"+MyAccNum+"'";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/atmdb","root","");
                St=con.createStatement();
                Rs=St.executeQuery(Query);
                if(Rs.next()) {
                    oldbalance = Rs.getInt(9);
                    bal.setText("Rs. "+oldbalance);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fc100 = new javax.swing.JButton();
        fc1000 = new javax.swing.JButton();
        fc5000 = new javax.swing.JButton();
        fc500 = new javax.swing.JButton();
        fc2000 = new javax.swing.JButton();
        fc10000 = new javax.swing.JButton();
        JLABEL = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(101, 205, 205));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("NMIT BANK");

        jLabel10.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("ATM MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel10)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        jLabel12.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("FAST CASH");

        fc100.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        fc100.setForeground(new java.awt.Color(0, 51, 102));
        fc100.setText("Rs. 100");
        fc100.setMaximumSize(new java.awt.Dimension(255, 37));
        fc100.setMinimumSize(new java.awt.Dimension(255, 37));
        fc100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fc100MouseClicked(evt);
            }
        });
        fc100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc100ActionPerformed(evt);
            }
        });

        fc1000.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        fc1000.setForeground(new java.awt.Color(0, 51, 102));
        fc1000.setText("Rs. 1000");
        fc1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fc1000MouseClicked(evt);
            }
        });
        fc1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc1000ActionPerformed(evt);
            }
        });

        fc5000.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        fc5000.setForeground(new java.awt.Color(0, 51, 102));
        fc5000.setText("Rs. 5000");
        fc5000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fc5000MouseClicked(evt);
            }
        });
        fc5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc5000ActionPerformed(evt);
            }
        });

        fc500.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        fc500.setForeground(new java.awt.Color(0, 51, 102));
        fc500.setText("Rs. 200");
        fc500.setMaximumSize(new java.awt.Dimension(255, 37));
        fc500.setMinimumSize(new java.awt.Dimension(255, 37));
        fc500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fc500MouseClicked(evt);
            }
        });

        fc2000.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        fc2000.setForeground(new java.awt.Color(0, 51, 102));
        fc2000.setText("Rs. 2000");
        fc2000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fc2000MouseClicked(evt);
            }
        });
        fc2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc2000ActionPerformed(evt);
            }
        });

        fc10000.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        fc10000.setForeground(new java.awt.Color(0, 51, 102));
        fc10000.setText("Rs. 10000");
        fc10000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fc10000MouseClicked(evt);
            }
        });
        fc10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc10000ActionPerformed(evt);
            }
        });

        JLABEL.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        JLABEL.setForeground(new java.awt.Color(0, 51, 102));
        JLABEL.setText("Balance:");

        jPanel5.setBackground(new java.awt.Color(101, 205, 205));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        logout.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 51, 102));
        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        bal.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 0, 0));
        bal.setText("Bal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fc1000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fc100, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc5000, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLABEL)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bal)
                                .addGap(29, 29, 29)))))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fc2000, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fc500, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fc10000, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fc500, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc100, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fc1000, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc2000, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fc5000, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fc10000, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(JLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fc100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fc100ActionPerformed

    private void fc2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc2000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fc2000ActionPerformed

    private void fc10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc10000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fc10000ActionPerformed

    private void fc1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fc1000ActionPerformed

    private void fc5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc5000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fc5000ActionPerformed

    private void fc100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fc100MouseClicked
        if(oldbalance < 100) {
            JOptionPane.showMessageDialog(this,"No Enough Balance");
        } else {
            try {
                String Query = "UPDATE accounttbl SET BAL=? WHERE ACC_NO=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/atmdb","root","");
                PreparedStatement ps = con.prepareStatement(Query);
                ps.setInt(1,oldbalance-100);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1)
                {
                    JOptionPane.showMessageDialog(this,"Balance Updated");
                    new MainMenu(MyAccNum).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Missing Information");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
            
        }
    }//GEN-LAST:event_fc100MouseClicked

    private void fc1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fc1000MouseClicked
        if(oldbalance < 1000) {
            JOptionPane.showMessageDialog(this,"No Enough Balance");
        } else {
            try {
                String Query = "UPDATE accounttbl SET BAL=? WHERE ACC_NO=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/atmdb","root","");
                PreparedStatement ps = con.prepareStatement(Query);
                ps.setInt(1,oldbalance-1000);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1)
                {
                    JOptionPane.showMessageDialog(this,"Balance Updated");
                    new MainMenu().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Missing Information");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
            
        }
    }//GEN-LAST:event_fc1000MouseClicked

    private void fc5000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fc5000MouseClicked
        if(oldbalance < 5000) {
            JOptionPane.showMessageDialog(this,"No Enough Balance");
        } else {
            try {
                String Query = "UPDATE accounttbl SET BAL=? WHERE ACC_NO=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/atmdb","root","");
                PreparedStatement ps = con.prepareStatement(Query);
                ps.setInt(1,oldbalance-5000);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1)
                {
                    JOptionPane.showMessageDialog(this,"Balance Updated");
                    new MainMenu().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Missing Information");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
            
        }
    }//GEN-LAST:event_fc5000MouseClicked

    private void fc500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fc500MouseClicked
        if(oldbalance < 500) {
            JOptionPane.showMessageDialog(this,"No Enough Balance");
        } else {
            try {
                String Query = "UPDATE accounttbl SET BAL=? WHERE ACC_NO=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/atmdb","root","");
                PreparedStatement ps = con.prepareStatement(Query);
                ps.setInt(1,oldbalance-500);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1)
                {
                    JOptionPane.showMessageDialog(this,"Balance Updated");
                    new MainMenu().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Missing Information");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
            
        }
    }//GEN-LAST:event_fc500MouseClicked

    private void fc2000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fc2000MouseClicked
        if(oldbalance < 2000) {
            JOptionPane.showMessageDialog(this,"No Enough Balance");
        } else {
            try {
                String Query = "UPDATE accounttbl SET BAL=? WHERE ACC_NO=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/atmdb","root","");
                PreparedStatement ps = con.prepareStatement(Query);
                ps.setInt(1,oldbalance-2000);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1)
                {
                    JOptionPane.showMessageDialog(this,"Balance Updated");
                    new MainMenu().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Missing Information");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
            
        }
    }//GEN-LAST:event_fc2000MouseClicked

    private void fc10000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fc10000MouseClicked
        if(oldbalance < 10000) {
            JOptionPane.showMessageDialog(this,"No Enough Balance");
        } else {
            try {
                String Query = "UPDATE accounttbl SET BAL=? WHERE ACC_NO=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/atmdb","root","");
                PreparedStatement ps = con.prepareStatement(Query);
                ps.setInt(1,oldbalance-10000);
                ps.setInt(2,MyAccNum);
                if(ps.executeUpdate() == 1)
                {
                    JOptionPane.showMessageDialog(this,"Balance Updated");
                    new MainMenu().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this,"Missing Information");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,e);
            }
            
        }
    }//GEN-LAST:event_fc10000MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new LOGIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FASTCASH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLABEL;
    private javax.swing.JLabel bal;
    private javax.swing.JButton fc100;
    private javax.swing.JButton fc1000;
    private javax.swing.JButton fc10000;
    private javax.swing.JButton fc2000;
    private javax.swing.JButton fc500;
    private javax.swing.JButton fc5000;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables
}
